name: Build and Test Spring Boot

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Adjust the Java version as needed
          distribution: 'adopt'

      - name: Build Spring Boot project
        env:
          GEO_LOCATION_KEY_ACTION: ${{secrets.GEO_LOCATION_KEY}}
        run: GEO_LOCATION_KEY=GEO_LOCATION_KEY_ACTION ./gradlew build